SELECT YEAROFENROLMENT, MAX(AVG_GRADES)
	FROM STUDENT, (
		SELECT SID, AVG(GRADE) AS AVG_GRADES
		FROM PASSED_EXAM
		GROUP BY SID ) AVERAGES
	WHERE STUDENT.SID = AVERAGES.SID
	GROUP BY YEAROFENROLMENT;